---
title: "Report Part 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 1. Read in the file, making the gene identifiers the row names. Show a table of values for the first six genes



### 2. Make a new column which is the mean of the other columns. Show a table of values for the first six genes.




### 3. List the 10 genes with the highest mean expression



### 4. Determine the number of genes with a mean <10


### 5. Make a histogram plot of the mean values and include it into your report.


### 6. Import this csv file into an R object. What are the column names?


### 7. Calculate the mean and standard deviation of tree circumference at the start and end of the study at both sites





### 8. Make a box plot of tree circumference at the start and end of the study at both sites.




### 9. Calculate the mean growth over the last 10 years at each site


### 10. Use the t.test to estimate the p-value that the 10 year growth is different at the two sites.



